Lesson 2 skeleton
js-tasks-ru/htmlcss-20210916_ivansacara pull request #11
Opened 2021-09-26 17:27 UTC by ivansacara

2021-09-26 17:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-28 19:05 UTC, GSemikozov requested changes

2021-09-28 19:05 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.short {
здесь и ниже - оформлены независимые атомарные классы - и это конечно же не по БЭМ. Поэтому - нужно переписать их как модификаторы тех элементов в которым они относятся ;)

2021-09-29 18:28 UTC, ivansacara commented on 04-lection2/02-skeleton/skeleton.css
> +.short {
исправил

2021-09-29 19:47 UTC, GSemikozov approved these changes

2021-09-29 19:47 UTC, merged