Histogram Lesson 2
js-tasks-ru/htmlcss-20210916_ivansacara pull request #12
Opened 2021-09-27 20:19 UTC by ivansacara

2021-09-27 20:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-27 20:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-27 20:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-28 19:07 UTC, GSemikozov requested changes

2021-09-28 19:07 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  width: 100%;
все-таки желательно добавить flex-grow: 1 и flex-basis: 9px (на занятии объяснил почему это важно, но - если что, смогу еще раз подсказать)

2021-09-29 17:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-29 18:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-29 18:27 UTC, ivansacara commented on 04-lection2/01-histogram/histogram.css
> +  width: 100%;
решено

разобрался)

2021-09-29 18:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-29 19:48 UTC, GSemikozov approved these changes

2021-09-29 19:48 UTC, merged